tasks:
  - init: |
      echo 'TODO: build project'
      curl https://static.lamdera.com/bin/linux/lamdera -o /workspace/lamdera-realworld/lamdera
      chmod a+x /workspace/lamdera-realworld/lamdera
    command: |
      echo 'TODO: start app'
      yes | sudo apt install libncurses5
      ./lamdera live