tasks:
  - init: |
      echo 'TODO: build project'
      curl https://static.lamdera.com/bin/linux/lamdera -o /usr/local/bin/lamdera
      chmod a+x /usr/local/bin/lamdera
    command: |
      echo 'TODO: start app'
      lamdera live