tasks:
  - init: |
      echo 'TODO: build project'
      curl https://static.lamdera.com/bin/linux/lamdera -o ~/lamdera
      chmod a+x ~/lamdera
    command: |
      echo 'TODO: start app'
      ~/lamdera live
